services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: node-app
    ports:
      - "3001:3000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: postgres-db
    env_file:
      - ./.env
      - ./decrypted_env/.env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: