CREATE TABLE IF NOT EXISTS notification_user (
    id BIGSERIAL PRIMARY KEY,
		user_id VARCHAR(18) NOT NULL,
		user_name VARCHAR(100) NOT NULL,
		members_only_video BOOLEAN DEFAULT TRUE,
		collaboration BOOLEAN DEFAULT TRUE,
		disable BOOLEAN DEFAULT FALSE,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stream_schedule (
		id BIGSERIAL PRIMARY KEY,
		video_id VARCHAR(100) NOT NULL,
		stream_title VARCHAR(255) NOT NULL,
		stream_time TIMESTAMP NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);